controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_error:
    path: /error/{code}
    controller: App\Controller\ErrorController::index
    requirements:
        code: \d+
