# config/services.yaml

parameters:
    images_directory: '%kernel.project_dir%/public/uploads/car_images'
    s3_bucket_name: '%env(AWS_S3_BUCKET)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Aws\S3\S3Client:
        factory: ['Aws\S3\S3Client', 'factory']
        arguments:
            -
                version: 'latest'
                region: '%env(AWS_REGION)%'
                credentials:
                    key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret: '%env(AWS_SECRET_ACCESS_KEY)%'

    App\Controller\AdminController:
        arguments:
            $s3Client: '@Aws\S3\S3Client'
            $s3BucketName: '%s3_bucket_name%'
